name: Terraform Infrastructure

on:
  push:
    branches:
      - main 
      - 'feature/**'

  pull_request:
    branches:
      - main

jobs:
  ci-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint code
        run: flake8 app.py test_app.py

      - name: Run tests
        run: pytest test_app.py -c

